# Use an official Node runtime as the parent image
FROM node:lts

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the current directory contents into the container
COPY . .

# Copy the .env.local file
COPY .env.local .env.local

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run the app in development mode with hot reloading
CMD ["npm", "run", "dev"]
